CREATE TABLE IF NOT EXISTS clients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150)  NOT NULL,
  id_card INT  NOT NULL,
  dni VARCHAR(8)  NOT NULL,
  email VARCHAR(50)  NOT NULL,
  CONSTRAINT clients_pk PRIMARY KEY  (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(150) NOT NULL,
  name_city VARCHAR(50) NOT NULL,
  name_country VARCHAR(50) NOT NULL,
  name_money VARCHAR(50) NOT NULL,
  change_value_money FLOAT NOT NULL,
  kind_city_name VARCHAR(50) NOT NULL,
  kind_city_description VARCHAR(150) NOT NULL,
  price FLOAT NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  clients_id bigint UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  KEY plans_client_id(clients_id),
  CONSTRAINT FOREIGN KEY (clients_id) REFERENCES clients (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



