CREATE TABLE IF NOT EXISTS money (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150)  NOT NULL,
    change_value FLOAT NOT NULL,
    PRIMARY KEY  (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS country (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150)  NOT NULL,
    money_id bigint UNSIGNED NOT NULL,
    PRIMARY KEY  (id),
    KEY money_id(money_id),
    CONSTRAINT FOREIGN KEY (money_id) REFERENCES money (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS kind_city (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150)  NOT NULL,
    description VARCHAR(500) NOT NULL,
    PRIMARY KEY  (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS city (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150)  NOT NULL,
    country_id bigint UNSIGNED NOT NULL,
    kind_city_id bigint UNSIGNED NOT NULL,
    PRIMARY KEY  (id),
    KEY country_id(country_id),
    KEY kind_city_id(kind_city_id),
    CONSTRAINT FOREIGN KEY (country_id) REFERENCES country (id),
    CONSTRAINT FOREIGN KEY (kind_city_id) REFERENCES kind_city (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  price FLOAT NOT NULL,
  travel_days INT NOT NULL,
  city_id bigint UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  KEY city_id(city_id),
  CONSTRAINT FOREIGN KEY (city_id) REFERENCES city (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150)  NOT NULL,
  email VARCHAR(300)  NOT NULL,
  password VARCHAR(32)  NOT NULL,
  PRIMARY KEY(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  account_number INT  NOT NULL,
  dni VARCHAR(8)  NOT NULL,
  miles int NOT NULL, 
  user_id bigint UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  KEY user_id(user_id),
  CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id bigint UNSIGNED NOT NULL,
  price FLOAT NOT NULL,
  PRIMARY KEY(id),
  KEY client_id(client_id),
  CONSTRAINT FOREIGN KEY (client_id) REFERENCES clients (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS trip_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_id bigint UNSIGNED NOT NULL,
  client_id bigint UNSIGNED NOT NULL,
  plan_id bigint UNSIGNED NOT NULL,
  promotion bigint NOT NULL,
  PRIMARY KEY(id),
  KEY payment_id(payment_id),
  KEY client_id(client_id),
  KEY plan_id(plan_id),
  CONSTRAINT FOREIGN KEY (payment_id) REFERENCES payments (id),
  CONSTRAINT FOREIGN KEY (client_id) REFERENCES clients (id),
  CONSTRAINT FOREIGN KEY (plan_id) REFERENCES plans (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
